export enum BatchOperateEnum {
  DELETE = 'DELETE',
  ENABLE = 'ENABLE',
  DISABLE = 'DISABLE',
  RESET_PASSWORD = 'RESET_PASSWORD',
  ADD_WHITELIST = 'ADD_WHITELIST',
  REMOVE_WHITELIST = 'REMOVE_WHITELIST'
}
