/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      icon: 'ic:baseline-block',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      icon: 'ic:baseline-web-asset-off',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      icon: 'ic:baseline-wifi-off',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 99
    }
  },
  {
    name: 'ai',
    path: '/ai',
    component: 'layout.base',
    meta: {
      title: 'ai',
      i18nKey: 'route.ai',
      icon: 'mdi:brain',
      order: 15
    },
    children: [
      {
        name: 'ai_agent',
        path: '/ai/agent',
        component: 'view.ai_agent',
        meta: {
          title: 'ai_agent',
          i18nKey: 'route.ai_agent',
          icon: 'mdi:robot-outline',
          order: 1510
        }
      },
      {
        name: 'ai_model',
        path: '/ai/model',
        component: 'view.ai_model',
        meta: {
          title: 'ai_model',
          i18nKey: 'route.ai_model',
          icon: 'carbon:model-alt',
          order: 1520
        }
      }
    ]
  },
  {
    name: 'alova',
    path: '/alova',
    component: 'layout.base',
    meta: {
      title: 'alova',
      i18nKey: 'route.alova',
      icon: 'carbon:http',
      order: 70
    },
    children: [
      {
        name: 'alova_request',
        path: '/alova/request',
        component: 'view.alova_request',
        meta: {
          title: 'alova_request',
          i18nKey: 'route.alova_request',
          icon: 'bi:send-check',
          order: 7010
        }
      },
      {
        name: 'alova_scenes',
        path: '/alova/scenes',
        component: 'view.alova_scenes',
        meta: {
          title: 'alova_scenes',
          i18nKey: 'route.alova_scenes',
          icon: 'cbi:scene-dynamic',
          order: 7020
        }
      }
    ]
  },
  {
    name: 'authx',
    path: '/authx',
    component: 'layout.base',
    meta: {
      title: 'authx',
      i18nKey: 'route.authx',
      icon: 'mdi:shield-key-outline',
      order: 25
    },
    children: [
      {
        name: 'authx_configs',
        path: '/authx/configs',
        component: 'view.authx_configs',
        meta: {
          title: 'authx_configs',
          i18nKey: 'route.authx_configs',
          icon: 'mdi:cog-outline',
          order: 2510
        }
      },
      {
        name: 'authx_records',
        path: '/authx/records',
        component: 'view.authx_records',
        meta: {
          title: 'authx_records',
          i18nKey: 'route.authx_records',
          icon: 'mdi:login-variant',
          order: 2520
        }
      }
    ]
  },
  {
    name: 'function',
    path: '/function',
    component: 'layout.base',
    meta: {
      title: 'function',
      i18nKey: 'route.function',
      icon: 'icon-park-outline:all-application',
      order: 30
    },
    children: [
      {
        name: 'function_hide-child',
        path: '/function/hide-child',
        meta: {
          title: 'function_hide-child',
          i18nKey: 'route.function_hide-child',
          icon: 'material-symbols:filter-list-off',
          order: 3020
        },
        redirect: '/function/hide-child/one',
        children: [
          {
            name: 'function_hide-child_one',
            path: '/function/hide-child/one',
            component: 'view.function_hide-child_one',
            meta: {
              title: 'function_hide-child_one',
              i18nKey: 'route.function_hide-child_one',
              icon: 'material-symbols:filter-list-off',
              hideInMenu: true,
              activeMenu: 'function_hide-child'
            }
          },
          {
            name: 'function_hide-child_three',
            path: '/function/hide-child/three',
            component: 'view.function_hide-child_three',
            meta: {
              title: 'function_hide-child_three',
              i18nKey: 'route.function_hide-child_three',
              hideInMenu: true,
              activeMenu: 'function_hide-child'
            }
          },
          {
            name: 'function_hide-child_two',
            path: '/function/hide-child/two',
            component: 'view.function_hide-child_two',
            meta: {
              title: 'function_hide-child_two',
              i18nKey: 'route.function_hide-child_two',
              hideInMenu: true,
              activeMenu: 'function_hide-child'
            }
          }
        ]
      },
      {
        name: 'function_multi-tab',
        path: '/function/multi-tab',
        component: 'view.function_multi-tab',
        meta: {
          title: 'function_multi-tab',
          i18nKey: 'route.function_multi-tab',
          icon: 'ic:round-tab',
          hideInMenu: true,
          activeMenu: 'function_tab',
          multiTab: true
        }
      },
      {
        name: 'function_request',
        path: '/function/request',
        component: 'view.function_request',
        meta: {
          title: 'function_request',
          i18nKey: 'route.function_request',
          icon: 'carbon:network-overlay',
          order: 3030
        }
      },
      {
        name: 'function_super-page',
        path: '/function/super-page',
        component: 'view.function_super-page',
        meta: {
          title: 'function_super-page',
          i18nKey: 'route.function_super-page',
          icon: 'ic:round-supervisor-account',
          order: 3050,
          roles: [ 'R_SUPER' ]
        }
      },
      {
        name: 'function_tab',
        path: '/function/tab',
        component: 'view.function_tab',
        meta: {
          title: 'function_tab',
          i18nKey: 'route.function_tab',
          icon: 'ic:round-tab',
          order: 3010
        }
      },
      {
        name: 'function_toggle-auth',
        path: '/function/toggle-auth',
        component: 'view.function_toggle-auth',
        meta: {
          title: 'function_toggle-auth',
          i18nKey: 'route.function_toggle-auth',
          icon: 'ic:round-construction',
          order: 3040
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 10
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      icon: 'icon-park-solid:web-page',
      keepAlive: true,
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|passkey-login|2fa|callback|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      icon: 'icon-park-solid:baokemeng',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'multi-menu',
    path: '/multi-menu',
    component: 'layout.base',
    meta: {
      title: 'multi-menu',
      i18nKey: 'route.multi-menu',
      icon: 'icon-park-solid:broadcast-one',
      order: 80
    },
    children: [
      {
        name: 'multi-menu_first',
        path: '/multi-menu/first',
        meta: {
          title: 'multi-menu_first',
          i18nKey: 'route.multi-menu_first',
          order: 8010
        },
        children: [
          {
            name: 'multi-menu_first_child',
            path: '/multi-menu/first/child',
            component: 'view.multi-menu_first_child',
            meta: {
              title: 'multi-menu_first_child',
              i18nKey: 'route.multi-menu_first_child',
              order: 801010
            }
          }
        ]
      },
      {
        name: 'multi-menu_second',
        path: '/multi-menu/second',
        meta: {
          title: 'multi-menu_second',
          i18nKey: 'route.multi-menu_second',
          order: 8020
        },
        children: [
          {
            name: 'multi-menu_second_child',
            path: '/multi-menu/second/child',
            meta: {
              title: 'multi-menu_second_child',
              i18nKey: 'route.multi-menu_second_child',
              order: 802010
            },
            children: [
              {
                name: 'multi-menu_second_child_home',
                path: '/multi-menu/second/child/home',
                component: 'view.multi-menu_second_child_home',
                meta: {
                  title: 'multi-menu_second_child_home',
                  i18nKey: 'route.multi-menu_second_child_home',
                  order: 802020
                }
              }
            ]
          }
        ]
      }
    ]
  },
  {
    name: 'plugin',
    path: '/plugin',
    component: 'layout.base',
    meta: {
      title: '插件示例',
      i18nKey: 'route.plugin',
      icon: 'clarity:plugin-line',
      order: 50
    },
    children: [
      {
        name: 'plugin_barcode',
        path: '/plugin/barcode',
        component: 'view.plugin_barcode',
        meta: {
          title: 'plugin_barcode',
          i18nKey: 'route.plugin_barcode',
          icon: 'ic:round-barcode',
          order: 5010
        }
      },
      {
        name: 'plugin_charts',
        path: '/plugin/charts',
        meta: {
          title: 'plugin_charts',
          i18nKey: 'route.plugin_charts',
          icon: 'mdi:chart-areaspline',
          order: 5020
        },
        children: [
          {
            name: 'plugin_charts_antv',
            path: '/plugin/charts/antv',
            component: 'view.plugin_charts_antv',
            meta: {
              title: 'plugin_charts_antv',
              i18nKey: 'route.plugin_charts_antv',
              icon: 'hugeicons:flow-square',
              order: 502010
            }
          },
          {
            name: 'plugin_charts_echarts',
            path: '/plugin/charts/echarts',
            component: 'view.plugin_charts_echarts',
            meta: {
              title: 'plugin_charts_echarts',
              i18nKey: 'route.plugin_charts_echarts',
              icon: 'simple-icons:apacheecharts',
              order: 502020
            }
          },
          {
            name: 'plugin_charts_vchart',
            path: '/plugin/charts/vchart',
            component: 'view.plugin_charts_vchart',
            meta: {
              title: 'plugin_charts_vchart',
              i18nKey: 'route.plugin_charts_vchart',
              localIcon: 'visactor',
              order: 502030
            }
          }
        ]
      },
      {
        name: 'plugin_copy',
        path: '/plugin/copy',
        component: 'view.plugin_copy',
        meta: {
          title: 'plugin_copy',
          i18nKey: 'route.plugin_copy',
          icon: 'mdi:clipboard-outline',
          order: 5030
        }
      },
      {
        name: 'plugin_editor',
        path: '/plugin/editor',
        meta: {
          title: 'plugin_editor',
          i18nKey: 'route.plugin_editor',
          icon: 'icon-park-outline:editor',
          order: 5040
        },
        children: [
          {
            name: 'plugin_editor_markdown',
            path: '/plugin/editor/markdown',
            component: 'view.plugin_editor_markdown',
            meta: {
              title: 'plugin_editor_markdown',
              i18nKey: 'route.plugin_editor_markdown',
              icon: 'ri:markdown-line',
              order: 504010
            }
          },
          {
            name: 'plugin_editor_quill',
            path: '/plugin/editor/quill',
            component: 'view.plugin_editor_quill',
            meta: {
              title: 'plugin_editor_quill',
              i18nKey: 'route.plugin_editor_quill',
              icon: 'mdi:file-document-edit-outline',
              order: 504020
            }
          }
        ]
      },
      {
        name: 'plugin_excel',
        path: '/plugin/excel',
        component: 'view.plugin_excel',
        meta: {
          title: 'plugin_excel',
          i18nKey: 'route.plugin_excel',
          icon: 'ri:file-excel-2-line',
          keepAlive: true,
          order: 5050
        }
      },
      {
        name: 'plugin_gantt',
        path: '/plugin/gantt',
        meta: {
          title: 'plugin_gantt',
          i18nKey: 'route.plugin_gantt',
          icon: 'ant-design:bar-chart-outlined',
          order: 5060
        },
        children: [
          {
            name: 'plugin_gantt_dhtmlx',
            path: '/plugin/gantt/dhtmlx',
            component: 'view.plugin_gantt_dhtmlx',
            meta: {
              title: 'plugin_gantt_dhtmlx',
              i18nKey: 'route.plugin_gantt_dhtmlx',
              order: 506010
            }
          },
          {
            name: 'plugin_gantt_vtable',
            path: '/plugin/gantt/vtable',
            component: 'view.plugin_gantt_vtable',
            meta: {
              title: 'plugin_gantt_vtable',
              i18nKey: 'route.plugin_gantt_vtable',
              localIcon: 'visactor',
              order: 506020
            }
          }
        ]
      },
      {
        name: 'plugin_icon',
        path: '/plugin/icon',
        component: 'view.plugin_icon',
        meta: {
          title: 'plugin_icon',
          i18nKey: 'route.plugin_icon',
          localIcon: 'custom-icon',
          order: 5070
        }
      },
      {
        name: 'plugin_map',
        path: '/plugin/map',
        component: 'view.plugin_map',
        meta: {
          title: 'plugin_map',
          i18nKey: 'route.plugin_map',
          icon: 'mdi:map',
          order: 5080
        }
      },
      {
        name: 'plugin_pdf',
        path: '/plugin/pdf',
        component: 'view.plugin_pdf',
        meta: {
          title: 'plugin_pdf',
          i18nKey: 'route.plugin_pdf',
          icon: 'uiw:file-pdf',
          order: 5090
        }
      },
      {
        name: 'plugin_pinyin',
        path: '/plugin/pinyin',
        component: 'view.plugin_pinyin',
        meta: {
          title: 'plugin_pinyin',
          i18nKey: 'route.plugin_pinyin',
          icon: 'entypo-social:google-hangouts',
          order: 5091
        }
      },
      {
        name: 'plugin_print',
        path: '/plugin/print',
        component: 'view.plugin_print',
        meta: {
          title: 'plugin_print',
          i18nKey: 'route.plugin_print',
          icon: 'mdi:printer',
          order: 5092
        }
      },
      {
        name: 'plugin_swiper',
        path: '/plugin/swiper',
        component: 'view.plugin_swiper',
        meta: {
          title: 'plugin_swiper',
          i18nKey: 'route.plugin_swiper',
          icon: 'simple-icons:swiper',
          order: 5093
        }
      },
      {
        name: 'plugin_tables',
        path: '/plugin/tables',
        meta: {
          title: 'plugin_tables',
          i18nKey: 'route.plugin_tables',
          icon: 'icon-park-outline:table',
          order: 5094
        },
        children: [
          {
            name: 'plugin_tables_vtable',
            path: '/plugin/tables/vtable',
            component: 'view.plugin_tables_vtable',
            meta: {
              title: 'plugin_tables_vtable',
              i18nKey: 'route.plugin_tables_vtable',
              localIcon: 'visactor',
              order: 509410
            }
          }
        ]
      },
      {
        name: 'plugin_typeit',
        path: '/plugin/typeit',
        component: 'view.plugin_typeit',
        meta: {
          title: 'plugin_typeit',
          i18nKey: 'route.plugin_typeit',
          icon: 'mdi:typewriter',
          order: 5095
        }
      },
      {
        name: 'plugin_video',
        path: '/plugin/video',
        component: 'view.plugin_video',
        meta: {
          title: 'plugin_video',
          i18nKey: 'route.plugin_video',
          icon: 'mdi:video',
          order: 5096
        }
      }
    ]
  },
  {
    name: 'pro-naive',
    path: '/pro-naive',
    component: 'layout.base',
    meta: {
      title: 'pro-naive',
      i18nKey: 'route.pro-naive',
      icon: 'material-symbols-light:demography-outline-rounded',
      order: 60
    },
    children: [
      {
        name: 'pro-naive_form',
        path: '/pro-naive/form',
        meta: {
          title: 'pro-naive_form',
          i18nKey: 'route.pro-naive_form',
          icon: 'fluent:form-28-regular',
          order: 6010
        },
        children: [
          {
            name: 'pro-naive_form_basic',
            path: '/pro-naive/form/basic',
            component: 'view.pro-naive_form_basic',
            meta: {
              title: 'pro-naive_form_basic',
              i18nKey: 'route.pro-naive_form_basic',
              order: 601010
            }
          },
          {
            name: 'pro-naive_form_query',
            path: '/pro-naive/form/query',
            component: 'view.pro-naive_form_query',
            meta: {
              title: 'pro-naive_form_query',
              i18nKey: 'route.pro-naive_form_query',
              order: 601020
            }
          },
          {
            name: 'pro-naive_form_step',
            path: '/pro-naive/form/step',
            component: 'view.pro-naive_form_step',
            meta: {
              title: 'pro-naive_form_step',
              i18nKey: 'route.pro-naive_form_step',
              order: 601030
            }
          }
        ]
      },
      {
        name: 'pro-naive_table',
        path: '/pro-naive/table',
        meta: {
          title: 'pro-naive_table',
          i18nKey: 'route.pro-naive_table',
          icon: 'mynaui:table',
          order: 6020
        },
        children: [
          {
            name: 'pro-naive_table_remote',
            path: '/pro-naive/table/remote',
            component: 'view.pro-naive_table_remote',
            meta: {
              title: 'pro-naive_table_remote',
              i18nKey: 'route.pro-naive_table_remote',
              order: 602010
            }
          },
          {
            name: 'pro-naive_table_row-edit',
            path: '/pro-naive/table/row-edit',
            component: 'view.pro-naive_table_row-edit',
            meta: {
              title: 'pro-naive_table_row-edit',
              i18nKey: 'route.pro-naive_table_row-edit',
              order: 602020
            }
          }
        ]
      }
    ]
  },
  {
    name: 'system-manage',
    path: '/system-manage',
    component: 'layout.base',
    meta: {
      title: 'system-manage',
      i18nKey: 'route.system-manage',
      icon: 'carbon:cloud-service-management',
      order: 20,
      roles: [ 'R_ADMIN' ]
    },
    children: [
      {
        name: 'system-manage_apis',
        path: '/system-manage/apis',
        component: 'view.system-manage_apis',
        meta: {
          title: 'system-manage_apis',
          i18nKey: 'route.system-manage_apis',
          icon: 'hugeicons:api',
          order: 2050
        }
      },
      {
        name: 'system-manage_buttons',
        path: '/system-manage/buttons',
        component: 'view.system-manage_buttons',
        meta: {
          title: 'system-manage_buttons',
          i18nKey: 'route.system-manage_buttons',
          icon: 'ph:mouse-middle-click',
          order: 2040
        }
      },
      {
        name: 'system-manage_menus',
        path: '/system-manage/menus',
        component: 'view.system-manage_menus',
        meta: {
          title: 'system-manage_menus',
          i18nKey: 'route.system-manage_menus',
          icon: 'material-symbols:route',
          keepAlive: true,
          order: 2030
        }
      },
      {
        name: 'system-manage_roles',
        path: '/system-manage/roles',
        component: 'view.system-manage_roles',
        meta: {
          title: 'system-manage_roles',
          i18nKey: 'route.system-manage_roles',
          icon: 'carbon:user-role',
          order: 2020,
          roles: [ 'R_SUPER' ]
        }
      },
      {
        name: 'system-manage_user-detail',
        path: '/system-manage/user-detail/:id',
        component: 'view.system-manage_user-detail',
        props: true,
        meta: {
          title: 'system-manage_user-detail',
          i18nKey: 'route.system-manage_user-detail',
          icon: 'icon-park-solid:address-book',
          hideInMenu: true,
          activeMenu: 'system-manage_users',
          roles: [ 'R_ADMIN' ]
        }
      },
      {
        name: 'system-manage_users',
        path: '/system-manage/users',
        component: 'view.system-manage_users',
        meta: {
          title: 'system-manage_users',
          i18nKey: 'route.system-manage_users',
          icon: 'ic:round-manage-accounts',
          order: 2010,
          roles: [ 'R_ADMIN' ]
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      icon: 'ph:user-circle',
      hideInMenu: true,
      activeMenu: 'system-manage_users',
      order: 11
    }
  }
];
